### PR TITLE
Adding More Adapt perms for blacklisting

### PR DESCRIPTION
**Pull request by NextdoorPsycho**
Adapt Blacklisting pr

## Modifying Plugin

**Plugin Name:** Adapt - Skills Leveling and Abilities
**Permissions Page:** [*Link to permission page*](https://docs.volmit.com/adapt/config/adaptions-skills/api-and-skill-blacklisting)

**plugin.yml**

```
name: ${name}
main: com.volmit.adapt.Adapt
version: ${version}
authors: [ NextdoorPsycho, Cyberpwn,  Vatuu ]
api-version: ${apiversion}
softdepend: [ PlaceholderAPI, WorldGuard, Factions, ChestProtect, Residence ]
libraries:
  - com.googlecode.concurrentlinkedhashmap:concurrentlinkedhashmap-lru:1.4.2
  - org.apache.commons:commons-lang3:3.12.0
  - com.google.code.gson:gson:2.8.9
  - com.elmakers.mine.bukkit:EffectLib:9.4
  - org.bitbucket.mstrobel:procyon-core:0.6.0
  - org.bitbucket.mstrobel:procyon-compilertools:0.6.0
  - org.bitbucket.mstrobel:procyon-reflection:0.6.0
  - org.zeroturnaround:zt-zip:1.15
commands:
  adapt:
    aliases: [ a, ada ]
```
### What Changes Did You Make?

Added: A bunch of backlisted perms

### CODE REVIEW

**Comment by Greazi-Times** [comment]
I see that you have closed this request.
But do you still want this to be merged?

**Comment by NextdoorPsycho** [comment]
I just added it manually

**Comment by Greazi-Times** [comment]
But do you want it to be added to the main database for other users?

**Comment by NextdoorPsycho** [comment]
I tested the uperms plugin, with the plugin yml import- i can still import
them, but if i do that then i need to maintain 2 repos no?

**Pull request closed without merging**
